# Generated by Django 4.1.7 on 2023-03-27 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytodo', '0002_alter_todomodel_is_done'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todomodel',
            options={'ordering': ('is_done', 'date_ending')},
        ),
        migrations.AlterField(
            model_name='todomodel',
            name='content',
            field=models.TextField(blank=True, verbose_name='Content'),
        ),
    ]
